version: '3'
services:
  redis-server: 
    image: 'redis:latest'
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
  node-app:
    build: ./server/
    environment:
    - NODE_ENV=production
    - PORT=8345
    volumes:
      - ./server/source:/usr/server/
    ports:
      - "3000:8345"
  frontend:
    build: ./client/
    environment:
    - NODE_ENV=production
    - PORT=8081
    volumes:
      - ./client/source:/usr/client/
    ports:
      - "3001:8081"